# Generated by Django 5.2.4 on 2025-08-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employerprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(choices=[('S', 'Sittway'), ('MO', 'MraukOo'), ('MB', 'MinBra')], default='S', max_length=2),
        ),
    ]
